# Generated by Django 5.1.3 on 2024-11-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='regime',
            field=models.CharField(choices=[('Private', 'Private'), ('Military', 'Military'), ('Commercial', 'Commercial')], default='Commercial', help_text='Type of flight regime', max_length=10),
        ),
    ]
