# Generated by Django 5.1.3 on 2024-11-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flights_regime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flights',
            options={'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
    ]
