# Generated by Django 5.1.3 on 2024-11-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flights_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='aircraft_type',
            field=models.CharField(max_length=15),
        ),
    ]
