# Generated by Django 5.1.3 on 2024-11-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(max_length=4, unique=True)),
                ('iata_code', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('abbreviated_name', models.CharField(blank=True, max_length=50, null=True)),
                ('altitude', models.IntegerField(help_text='In feet')),
                ('runway_length', models.IntegerField(help_text='In metres')),
                ('runway_width', models.IntegerField(help_text='In metres')),
                ('tower_frequency', models.CharField(help_text='In MHz. If more than 1, separate by |, e.g. 131,5|879,5|987,5', max_length=5)),
                ('acc_frequency', models.CharField(help_text='In KHz. If more than 1, separate by |, e.g. 1315|8795|9875', max_length=100)),
            ],
        ),
    ]
