# Generated by Django 5.1.3 on 2024-12-05 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0003_metar_sigmet_taf'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notams', to='airports.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravitas', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('impact_type', models.CharField(choices=[('Airport Closure', 'Airport Cosure'), ('Runway Closure', 'Runway Closure'), ('Weather Impact', 'Weather Impact'), ('System Outage', 'System Outage'), ('Other Reason', 'Other Reason')], max_length=50)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='airports.airport')),
                ('notam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='airports.notam')),
            ],
        ),
    ]
